---
#
# ci/pipeline.yml
#
# Pipeline structure file for a Docker Image pipeline
#
# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
#
# author:  James Hunt <james@niftylogic.com>
#          Dennis Bell <dennis.j.bell@gmail.com>
# created: 2016-03-04

meta:
  name:     (( param "Please name your pipeline" ))
  release:  (( grab meta.name ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  url:      (( param "Please specify the full url of the target Concourse CI" ))
  pipeline: (( grab meta.name ))

  image:    starkandwayne/concourse

  aws:
    bucket:     (( concat meta.name "-pipeline" ))
    access_key: (( param "Please set your AWS Access Key ID" ))
    secret_key: (( param "Please set your AWS Secret Key ID" ))

  source:
    github:
      uri:          (( concat "git@github.com:" meta.source.github.owner "/" meta.source.github.repo ))
      owner:        (( param "Please specify the name of the user / organization that owns the Github repository for the source" ))
      repo:         (( param "Please specify the name of the Github repository for the source" ))
      branch:       master
      private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
      access_token: (( param "Please generate a Personal Access Token and specify it here" ))

  tests:
    github:
      uri:          (( concat "git@github.com:" meta.tests.github.owner "/" meta.tests.github.repo ))
      owner:        (( grab meta.source.github.owner ))
      repo:         (( grab meta.source.github.repo ))
      branch:       (( grab meta.source.github.branch ))
      private_key:  (( grab meta.source.github.private_key ))
    cmd:            (( param "Please specify the executable for the test" ))
    args:           (( param "Please specify the arguments (as an array) for the test command" ))

  dockerhub:
    email:      (( param "Please specify the email address for your Dockerhub account" ))
    username:   (( param "Please specify the username for your Dockerhub account" ))
    password:   (( param "Please specify the password for your Dockerhub account" ))
    repository: (( param "Please specify the name of the image (repo/name) that you are building" ))

  slack:
    webhook:         (( param "Please specify your Slack Incoming Webhook Integration URL" ))
    channel:         (( param "Please specify the channel (#name) or user (@user) to send messages to" ))
    username:        concourse
    icon:            https://cl.ly/2F421Y300u07/concourse-logo-blue-transparent.png
    build_fail_msg: '(( concat ":concourse-fail: <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Failed to build " meta.name "!  Click for details.>" ))'
    test_fail_msg:  '(( concat ":concourse-fail: <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Failed " meta.name " tests!  Click for details.>" ))'

groups:
  - name: (( grab meta.name ))
    jobs:
      - build
      - promote
      - minor
      - major
      - test

jobs:
  - name: build
    public: true
    serial: true
    plan:
      - get: source
        trigger: true
      - put: edge
        params: { build: source }
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     (( grab meta.slack.build_fail_msg ))

  - name: test
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: tests }
          - { get: edge,    passed: [build], trigger: true }
          - { get: source,  passed: [build] }
      - task: test-image
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              .: (( inject meta.dockerhub ))
              tag:  edge
          inputs:
            - name: source
            - name: tests
          run:
            path: (( grab meta.tests.cmd ))
            args: (( grab meta.tests.args ))
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     (( grab meta.slack.test_fail_msg ))

  - name: minor
    public: true
    plan:
      - { get: version, trigger: false, params: {bump: minor} }
      - { put: version,                 params: {file: version/number} }

  - name: major
    public: true
    plan:
      - { get: version, trigger: false, params: {bump: major} }
      - { put: version,                 params: {file: version/number} }

  - name: promote
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: version }
          - { get: edge,    passed: [test], params: { save: true } }
          - { get: source,  passed: [test] }

      - task: release
        config:
          image_resource:
            type: docker-image
            source:
              repository: (( grab meta.image ))
          platform: linux
          inputs:
            - name: source
            - name: version
          outputs:
            - name: gh
            - name: pushme
          run:
            path: ./source/ci/scripts/release
            args: []
          params:
            REPO_ROOT:    source
            RELEASE_ROOT: gh
            RELEASE_NAME: (( grab meta.release ))
            REPO_OUT:     pushme/source
            VERSION_FROM: version/number

      - put: latest # as 'latest'
        params:
          load:       edge

      - put: latest # as 'vX.Y.Z'
        params:
          tag:             version/number
          tag_prefix:      v
          load:       edge

      - put: version
        params:
          bump: patch
      - put: source
        params:
          rebase: true
          repository: pushme/source
      - put: github
        params:
          name: gh/name
          tag:  gh/tag
          body: gh/notes.md

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: source
    type: git
    source:
      uri:         (( grab meta.source.github.uri ))
      branch:      (( grab meta.source.github.branch ))
      private_key: (( grab meta.source.github.private_key ))

  - name: tests
    type: git
    source:
      uri:         (( grab meta.tests.github.uri ))
      branch:      (( grab meta.tests.github.branch ))
      private_key: (( grab meta.tests.github.private_key ))

  - name: edge
    type: docker-image
    source:
      .: (( inject meta.dockerhub ))
      tag: edge

  - name: latest
    type: docker-image
    source:
      .: (( inject meta.dockerhub ))
      tag: latest

  - name: version
    type: semver
    source:
      driver:            s3
      bucket:            (( grab meta.aws.bucket ))
      key:               version
      access_key_id:     (( grab meta.aws.access_key ))
      secret_access_key: (( grab meta.aws.secret_key ))
      initial_version:   (( grab meta.initial_version || "0.0.1" ))

  - name: notify
    type: slack-notification
    source:
      url: (( grab meta.slack.webhook ))

  - name: github
    type: github-release
    source:
      user:         (( grab meta.source.github.owner ))
      repository:   (( grab meta.source.github.repo ))
      access_token: (( grab meta.source.github.access_token ))
